# -*- coding: utf-8 -*-
"""escopo_funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QBULpdVi-u51ffDX-IyzJ6KpRDNodKlO

# Escopo de funções
"""

letra = 'a'

def fn_qualquer():
  letra = 'b'
  print(letra)

fn_qualquer()
print(letra)

"""# Dicionários"""

carro = {'modelo': 'celta', 'ano': 2000}

# print(carro['modelo'])
# print(carro['ano'])

for chave, valor, in carro.items():
  print(chave)
  print(valor)

"""None usa para representar algum campo que nao esta preenchido

:: Stride, utilizada para fazer fatiamento.
Ex: [::-1] fatiamento da lista do fim ao início e o -1 é inverter o valor da lista.

Objeto é um fruto de uma instanciação de uma classe. O dicionário não partiu de uma instanciação de uma classe, também serve para agrupar informações e comportamentos.
"""

import csv

def carregar_arquivo(arquivo):
  return open(arquivo, newline='')

def obter_dados(arquivo):
  leitor = csv.DictReader(arquivo, delimiter=',')
  return leitor

arquivo_csv = carregar_arquivo('CarRentalData.csv')
dados = obter_dados(arquivo_csv)

for carro in dados:
  print(dict(carro))

import csv

def carregar_arquivo(arquivo):
  return open(arquivo, newline='')

def obter_dados(arquivo):
  leitor = csv.DictReader(arquivo, delimiter=',')
  return leitor

arquivo_csv = carregar_arquivo('CarRentalData.csv')
dados = obter_dados(arquivo_csv)

teslas_alugados = 0

for carro in dados:
  carro = dict(carro)
  if carro['vehicle.make'] == 'Tesla':
    teslas_alugados += 1

print(teslas_alugados)

"""+= É igual a teslas_alugados + 1"""

import csv

def carregar_arquivo(arquivo):
  return open(arquivo, newline='')

def obter_dados(arquivo):
  leitor = csv.DictReader(arquivo, delimiter=',')
  return leitor

arquivo_csv = carregar_arquivo('CarRentalData.csv')
dados = obter_dados(arquivo_csv)

print(dict(next(dados)))

s = 'King Arthur'
s[::2]