# -*- coding: utf-8 -*-
"""listas_e_strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lcu7GzoYclMb11ACvo8n5bqHCRMJpAzZ
"""

lista1 = [10,20,30,40]
type(lista1)

lista1[0]

lista1[1]

lista1[2]

lista1[3]

"""Servem para conseguir guardar vários valores e guarda-los.

Com python da para pegar esses valores sem reescreve-los atraves da iteração.
"""

for numero in lista1:
  dobro = numero * 2
  print(numero)
  print(dobro)
  print('----')

"""Exemplo"""

zombies = ['z1', 'z2', 'z3', 'z4']

for zombie in zombies:
  print('Nome:', zombie)

zombies = ['z2', 'z1', 'z4', 'z3']

for zombie in zombies:
  print('Nome: ', zombie)

print(zombies)
zombies.sort()
print(zombies)

zombies[1:3]

nome = 'daniel da kenzie'
print(nome[0])
print(nome[4])
print(nome[0:4])

nome.upper()

nome.title()

for letra in nome:
  print('Letra:', letra)

def soma():
  pass

len(zombies)
zombies[:3]
del zombies[2]
zombies

del zombies[2] # esta linha remove o elemento
print(zombies)

nome[::-1]

numeros_em_tuplas = (1,2,3,4,5)
print(numeros_em_tuplas)

lista1.sort(reverse=True)
lista1