# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yzL9quD7-cJi9k2pRrm5cBl6XeiHS-zd

# Como criar uma variável
"""

variavel = 2
print(variavel)
type(variavel)

"""# Variável com valor real"""

preco_do_produto = 2.5
print(preco_do_produto)
type(preco_do_produto)

"""# Variável String"""

variavel = "texto"
print(variavel)

"""# Variavel Boolean

"""

verdadeiro = True
falso = False
print(verdadeiro)
print(falso)

"""# Listas"""

lista = [1,2,3,4,5,6,7,8]
print(lista)

lista2 = [True, False, True, True]
print(lista2)

lista_kenzie = [1, 'luan', 2, 'guilherme', True, 'daniel']
print(lista_kenzie)

"""# Condicionais

Se o 3 é maior que 3, imprime

*   é maior
*   foi
"""

if 3 > 2:
  print('é maior')
  print('foi')

"""E se a nossa condição não for aceita, o que fazemos?

Utilizamos o 'else'

"""

if 2 > 3:
  print('é maior')
  print('foi')
else:
    print('nao é maior')
    print('foi também')

"""# Usando variáveis"""

variavel_1 = 3
variavel_2 = 4
if variavel_1 < variavel_2:
  print('O valor na variável 1 é menor')

